import os
import time
import json
import concurrent.futures
import threading
from utils import (
    get_common_argparser,
    make_generate_config,
    parse_json_response,
    _retry_api_call, retry_parse_json,
    ensure_output_dir, load_processed_pairs,
    init_pipeline, load_jsonl, append_jsonl,
    load_summary_map, check_input_file,
    load_keypoints_by_content,
    print_pipeline_banner, print_pipeline_done,
)

# ───────────────────────────────────────────────
# Judge 시스템 프롬프트
# ───────────────────────────────────────────────

_DESC_JUDGE_SYSTEM_PROMPT = """You are an expert evaluator specializing in video scene description quality assessment.

You will be given:
- [Anchor]: A ground-truth detailed scene description written in Korean by a professional model (Pro-level), based on the actual video footage and metadata.
- [Candidate]: A scene description generated by an AI model in English, based on limited input sources (images only, multimodal, video clip, or text transcript).

Your task is to evaluate how accurately and completely the Candidate captures the key information from the Anchor.

NOTE ON EXTERNAL KNOWLEDGE IN DESCRIPTIONS:
- If the Candidate correctly identifies a person, place, or entity by their known name (using World Knowledge) that the Anchor also references, this should be evaluated positively.
- However, if the Candidate adds significant factual claims or contextual information NOT present in the Anchor AND NOT directly observable from the source input, treat this as potential hallucination and penalize under Factual Precision.
- The key distinction: Correct identification/naming = good. Invented narrative or unverifiable claims = bad.

Evaluate across 3 criteria, each scored 1–5:

**1. Scene Understanding**
How accurately does the Candidate identify and describe the visual scene: setting, characters, actions, objects, spatial layout, and camera composition?
- 5: Captures nearly all visual elements — scene composition, camera angles, character actions, objects, environment, colors, and on-screen text — with high precision.
- 4: Captures most visual elements with minor omissions or slight inaccuracies that do not distort the overall picture.
- 3: Captures the general visual situation but misses several specific details or contains noticeable inaccuracies.
- 2: Only captures basic or surface-level visual elements; significant details are missing or incorrect.
- 1: Mostly inaccurate, missing critical visual information, or contradicts what the Anchor describes.

**2. Factual Precision**
How accurately does the Candidate reflect verifiable facts: proper nouns (person names, place names, brand names), dialogue/narration content, numbers, and specific claims?
- 5: All key proper nouns, dialogue quotes, and factual claims match the Anchor with high fidelity.
- 4: Most facts are correct with minor omissions (e.g., one name missing), but NO fabricated information.
- 3: Gets core facts right but omits several important details, or contains 1–2 minor factual inaccuracies.
- 2: Contains multiple factual errors or significant omissions; some names, quotes, or claims are wrong.
- 1: Fabricates facts not present in the Anchor, severely misidentifies key entities, or is factually unreliable.
IMPORTANT: Fabrication (inventing facts not in the Anchor) must be penalized MORE harshly than omission (failing to mention facts). A description that omits a name is better than one that invents a wrong name.
CLARIFICATION: If the Candidate correctly identifies an entity using World Knowledge (e.g., recognizing a celebrity by face), and this identification is consistent with the Anchor, it should be scored positively. Penalize only verifiably incorrect or fabricated information.

**3. Narrative Completeness**
How completely does the Candidate cover the narrative arc of the scene: story progression, cause-effect relationships, emotional tone, and thematic nuances?
- 5: Fully captures the scene's narrative flow, cause-effect dynamics, emotional atmosphere, and thematic depth as described in the Anchor.
- 4: Covers the main narrative arc with minor gaps in emotional nuance or thematic depth.
- 3: Captures the basic storyline but misses important narrative transitions, emotional shifts, or thematic elements.
- 2: Only conveys a fragmented or superficial version of the narrative; major story beats or emotional context are absent.
- 1: Fails to convey any coherent narrative, or the described narrative contradicts the Anchor entirely.

Output ONLY the following JSON. No other text.
{
    "scene_understanding": {
        "rationale": "<Concise evaluation reasoning in English, citing specific evidence from Anchor vs Candidate>",
        "score": <integer 1-5>
    },
    "factual_precision": {
        "rationale": "<Concise evaluation reasoning in English, citing specific evidence from Anchor vs Candidate>",
        "score": <integer 1-5>
    },
    "narrative_completeness": {
        "rationale": "<Concise evaluation reasoning in English, citing specific evidence from Anchor vs Candidate>",
        "score": <integer 1-5>
    }
}"""


def make_kd_judge_config(thinking_level=None):
    """KeyScene Description Judge용 GenerateContentConfig를 반환합니다."""
    return make_generate_config(
        system_instruction=_DESC_JUDGE_SYSTEM_PROMPT,
        thinking_level=thinking_level
    )


def extract_current_scene_desc(kss_text):
    """KSS 텍스트에서 '[2. 현재 장면 묘사]' 섹션만 추출합니다."""
    tag = "[2. 현재 장면 묘사]"
    if tag in kss_text:
        return kss_text.split(tag)[-1].strip()
    return kss_text.strip()


def judge_one_description(
    client, args, judge_config,
    content_id, scene_idx, mode,
    candidate_text, anchor_text,
):
    """단일 (scene_idx, mode) Description을 평가하고 결과 record를 반환합니다.
    콘솔 출력과 파일 쓰기는 호출측에서 수행합니다."""
    if not anchor_text:
        return {"skipped": True, "reason": f"Scene {scene_idx}에 KSS Anchor 없음", "mode": mode}
    if not candidate_text or not candidate_text.strip():
        return {"skipped": True, "reason": f"Scene {scene_idx} mode={mode} Candidate 비어있음", "mode": mode}

    try:
        score_dict = retry_parse_json(
            lambda: _retry_api_call(
                lambda: client.models.generate_content(
                    model=args.kd_judge_model,
                    contents=[
                        "--- [Anchor] (Ground-truth KeyScene Summary, Korean) ---",
                        anchor_text,
                        "--- [Candidate] (AI-generated Description, English) ---",
                        candidate_text,
                        "--- Request ---",
                        "Evaluate the Candidate description against the Anchor using the 3 criteria defined in the system prompt. "
                        "Output ONLY the JSON with scene_understanding, factual_precision, and narrative_completeness scores.",
                    ],
                    config=judge_config
                ).text,
                label=f"KD Judge API ({mode}, Scene {scene_idx})"
            ),
            label=f"KD Judge JSON ({mode}, Scene {scene_idx})"
        )

        # 점수 집계
        _SCORE_KEYS = ["scene_understanding", "factual_precision", "narrative_completeness"]
        total = sum(
            (score_dict.get(k, {}).get("score", 0) if isinstance(score_dict.get(k), dict) else 0)
            for k in _SCORE_KEYS
        ) if score_dict else 0

        return {
            "content_id":  content_id,
            "scene_idx":   scene_idx,
            "mode":        mode,
            "total_score": total,
            "judge":       score_dict,
        }

    except Exception as e:
        return {"error": True, "reason": str(e), "mode": mode, "scene_idx": scene_idx}


def _print_judge_result(record):
    """Judge 결과 한 건을 콘솔에 출력합니다."""
    _ITEM_LABELS = [
        ("scene_understanding", "Scene Understanding"),
        ("factual_precision", "Factual Precision"),
        ("narrative_completeness", "Narrative Completeness"),
    ]
    mode  = record.get("mode", "?")
    s_idx = record.get("scene_idx", "?")

    if record.get("skipped"):
        print(f"[{mode}] Skip: {record.get('reason', '')}")
        return
    if record.get("error"):
        print(f"[{mode}] Error: {record.get('reason', '')}")
        return

    score_dict = record.get("judge", {})
    total      = record.get("total_score", 0)
    print(f"\n[{mode}] ", end="")
    if score_dict:
        scores = []
        for key, label in _ITEM_LABELS:
            item  = score_dict.get(key, {})
            score = item.get("score", "?") if isinstance(item, dict) else "?"
            scores.append(f"{label}={score}")
        print(f"Total: {total}/15 | " + " | ".join(scores))
        # rationale 상세 출력
        for key, label in _ITEM_LABELS:
            item = score_dict.get(key, {})
            rationale = item.get("rationale", "N/A") if isinstance(item, dict) else "N/A"
            score = item.get("score", "?") if isinstance(item, dict) else "?"
            print(f"- {label} ({score}/5): {rationale}")
    else:
        print(f"No scores (Total: {total}/15)")


# ───────────────────────────────────────────────
# Main
# ───────────────────────────────────────────────

def main():
    parser = get_common_argparser(description="KeyScene Description 4종을 KSS 앵커 기반으로 품질 평가합니다.")
    parser.add_argument("--kss_file", default="assets/keyscene_summary.jsonl",
                        help="KeyScene Summary JSONL 경로 (Anchor)")
    parser.add_argument("--kd_file", default="assets/keyscene_description.jsonl",
                        help="KeyScene Description JSONL 경로 (video_desc / raw_desc 소스)")
    parser.add_argument("--output_file", default="assets/keyscene_description_scores.jsonl",
                        help="Description Judge 점수 저장 경로")
    parser.add_argument("--keypoints_file", default="assets/keypoint_scenes.jsonl",
                        help="Keypoint Scene 목록 JSONL 경로")
    parser.add_argument("--watch", action="store_true",
                        help="kd_file을 모니터링하며 새로운 video_desc/raw_desc를 실시간으로 평가합니다.")
    parser.add_argument("--modes", nargs="+",
                        default=["img_desc", "mm_desc", "video_desc", "raw_desc"],
                        choices=["img_desc", "mm_desc", "video_desc", "raw_desc"],
                        help="평가할 모드 직접 지정 (기본값: 4종 모두)")

    args, client = init_pipeline(parser.parse_args())
    judge_config = make_kd_judge_config(thinking_level=args.kd_judge_thinking_level)

    ensure_output_dir(args.output_file)

    # 기처리분 로드: (content_id, scene_idx, mode) 단위
    processed_triples = set()
    for rec in load_jsonl(args.output_file):
        c_id  = rec.get("content_id")
        s_idx = rec.get("scene_idx")
        mode  = rec.get("mode")
        if c_id and s_idx is not None and mode:
            processed_triples.add((c_id, s_idx, mode))
    if processed_triples:
        print(f"[기처리] {len(processed_triples)}개 (content_id, scene_idx, mode) 쌍이 이미 처리됨.")

    # KSS Anchor 로드
    summary_map = load_summary_map(args.kss_file)
    if summary_map:
        print(f"[KSS Anchor] {len(summary_map)}개 Scene의 Summary 로드됨 ({args.kss_file})")
    else:
        print(f"[Warning] KSS 파일을 찾을 수 없거나 비어있습니다: {args.kss_file}")

    # Keypoint 목록 (필요 시 GCS 접근용)
    keypoints_by_content = {}
    if os.path.exists(args.keypoints_file):
        keypoints_by_content = load_keypoints_by_content(args.keypoints_file)

    print_pipeline_banner(
        f"KeyScene Description 품질 평가 파이프라인을 시작합니다. (Watch 모드: {args.watch})"
    )

    file_write_lock = threading.Lock()

    # 정규 모드 순서
    _MODE_ORDER = ["video_desc", "raw_desc", "img_desc", "mm_desc"]

    # ── keyscene_description.jsonl에서 4모드 통합 Judge ──────────────
    # generate_keyscene_description.py가 video_desc/raw_desc/img_desc/mm_desc를
    # 모두 동일 파일에 기록하므로, 소스를 분리할 필요 없이 한 루프로 처리합니다.

    if not os.path.exists(args.kd_file) and not args.watch:
        print(f"[Info] {args.kd_file} 파일이 존재하지 않습니다. 평가를 건너뜁니다.")
        print_pipeline_done(args.output_file)
        return

    last_position   = 0
    pipeline_done   = False
    total_evaluated = len(processed_triples)

    # Scene 단위로 후보 모드를 누적하는 버퍼: {(c_id, s_idx): {mode: candidate_text}}
    scene_buffer = {}

    try:
        while True:
            if not os.path.exists(args.kd_file):
                time.sleep(3)
                continue

            with open(args.kd_file, "r", encoding="utf-8") as f:
                f.seek(last_position)
                new_lines     = f.readlines()
                last_position = f.tell()

            for line in new_lines:
                if not line.strip():
                    continue
                try:
                    obj = json.loads(line)
                except json.JSONDecodeError:
                    continue

                if obj.get("pipeline_done"):
                    pipeline_done = True
                    continue

                c_id  = obj.get("content_id")
                s_idx = obj.get("scene_idx")
                mode  = obj.get("mode")
                desc  = obj.get("description", "")

                if not c_id or s_idx is None or not mode:
                    continue
                if mode not in args.modes:
                    continue
                if (c_id, s_idx, mode) in processed_triples:
                    continue

                scene_buffer.setdefault((c_id, s_idx), {})[mode] = desc

            # Scene 단위로 4모드가 모두 준비된 것(또는 pipeline_done 시 남은 것) Judge
            ready_scenes = []
            for (c_id, s_idx), mode_map in list(scene_buffer.items()):
                pending_modes = [
                    m for m in args.modes
                    if m in mode_map and (c_id, s_idx, m) not in processed_triples
                ]
                all_arrived = all(m in mode_map for m in args.modes)
                if all_arrived or pipeline_done:
                    if pending_modes:
                        ready_scenes.append((c_id, s_idx, pending_modes, mode_map))

            if ready_scenes:
                # Scene 단위로 병렬 Judge 후 정규 순서로 출력
                for c_id, s_idx, pending_modes, mode_map in ready_scenes:
                    kss_raw = summary_map.get((c_id, s_idx), "")
                    anchor  = extract_current_scene_desc(kss_raw) if kss_raw else ""
                    ordered = [m for m in _MODE_ORDER if m in pending_modes]

                    # Scene 단위 executor: 4모드 병렬 실행 → 전부 완료 후 출력
                    executor = concurrent.futures.ThreadPoolExecutor(max_workers=len(ordered))
                    try:
                        futures = {}
                        for mode in ordered:
                            candidate = mode_map[mode]
                            futures[mode] = executor.submit(
                                judge_one_description,
                                client, args, judge_config,
                                c_id, s_idx, mode,
                                candidate, anchor,
                            )

                        # Scene 헤더 출력
                        print(f"\n{'='*60}")
                        print(f"[Judge] '{c_id}' | Scene {s_idx}")
                        print(f"{'='*60}")

                        # 정규 순서로 결과 수집 & 출력
                        for mode in ordered:
                            try:
                                record = futures[mode].result()
                            except Exception as e:
                                print(f"[{mode}] Error: {e}")
                                with file_write_lock:
                                    processed_triples.add((c_id, s_idx, mode))
                                continue

                            _print_judge_result(record)

                            if record and not record.get("skipped") and not record.get("error"):
                                with file_write_lock:
                                    append_jsonl(args.output_file, record)
                                total_evaluated += 1

                            with file_write_lock:
                                processed_triples.add((c_id, s_idx, mode))
                    finally:
                        executor.shutdown(wait=False, cancel_futures=True)

                # 버퍼에서 완료된 Scene 제거
                for c_id, s_idx, pending_modes, _ in ready_scenes:
                    scene_buffer.pop((c_id, s_idx), None)

                print(f"\n▶ [Judge] 누적 평가 완료: {total_evaluated}개")

            if args.watch:
                if pipeline_done and not scene_buffer:
                    print("\n[Watch] pipeline_done 시그널 감지 및 버퍼 소진 완료. 종료합니다.")
                    break
                time.sleep(3)
            else:
                break

    except KeyboardInterrupt:
        print("\n\n사용자에 의해 중단되었습니다.")
        os._exit(1)

    print_pipeline_done(args.output_file)


if __name__ == "__main__":
    main()
