import os
import time
import json
import concurrent.futures
import threading
from utils import (
    get_common_argparser,
    make_generate_config,
    parse_json_response,
    _retry_api_call, retry_parse_json,
    ensure_output_dir, load_processed_pairs,
    init_pipeline, load_jsonl, append_jsonl,
    load_summary_map, check_input_file,
    get_gcs_descriptions_by_scene_idx,
    preload_content_metadata,
    load_keypoints_by_content,
    print_pipeline_banner, print_pipeline_done,
)

# ───────────────────────────────────────────────
# Judge 시스템 프롬프트
# ───────────────────────────────────────────────

_DESC_JUDGE_SYSTEM_PROMPT = """You are an expert evaluator specializing in video scene description quality assessment.

You will be given:
- [Anchor]: A ground-truth detailed scene description written in Korean by a professional model (Pro-level), based on the actual video footage and metadata.
- [Candidate]: A scene description generated by an AI model in English, based on limited input sources (images only, multimodal, video clip, or text transcript).

Your task is to evaluate how accurately and completely the Candidate captures the key information from the Anchor.

Evaluate across 2 criteria, each scored 1–5:

**1. Visual Accuracy**
How accurately does the Candidate describe the visual elements present in the scene?
- 5: Captures nearly all visual elements from the Anchor — scene composition, camera angles, character actions, objects, environment, colors, and on-screen text — with high precision.
- 4: Captures most visual elements with minor omissions or slight inaccuracies that do not distort the overall picture.
- 3: Captures the general visual situation but misses several specific details or contains noticeable inaccuracies.
- 2: Only captures basic or surface-level visual elements; significant details are missing or incorrect.
- 1: Mostly inaccurate, missing critical visual information, or contradicts what the Anchor describes.

**2. Contextual Detail**
How well does the Candidate reflect the contextual information: dialogue content, proper nouns (names, places, objects), narrative progression, and emotional/thematic nuances?
- 5: Accurately reflects key dialogue or narration, correct proper nouns, narrative context, and emotional/thematic nuances as described in the Anchor.
- 4: Captures most contextual details with minor omissions (e.g., a name missing or a dialogue paraphrase that slightly shifts meaning).
- 3: Gets the basic narrative right but misses important dialogue, misidentifies proper nouns, or lacks emotional nuance.
- 2: Captures only a fragment of the contextual information; significant facts, names, or narrative details are wrong or absent.
- 1: Fails to convey meaningful context, contains significant factual errors, or is entirely unrelated to the Anchor's content.

Output ONLY the following JSON. No other text.
{
    "visual_accuracy": {
        "rationale": "<Concise evaluation reasoning in English, citing specific evidence from Anchor vs Candidate>",
        "score": <integer 1-5>
    },
    "contextual_detail": {
        "rationale": "<Concise evaluation reasoning in English, citing specific evidence from Anchor vs Candidate>",
        "score": <integer 1-5>
    }
}"""


def make_kd_judge_config(thinking_level=None):
    """KeyScene Description Judge용 GenerateContentConfig를 반환합니다."""
    return make_generate_config(
        system_instruction=_DESC_JUDGE_SYSTEM_PROMPT,
        thinking_level=thinking_level
    )


def extract_current_scene_desc(kss_text):
    """KSS 텍스트에서 '[2. 현재 장면 묘사]' 섹션만 추출합니다."""
    tag = "[2. 현재 장면 묘사]"
    if tag in kss_text:
        return kss_text.split(tag)[-1].strip()
    return kss_text.strip()


def judge_one_description(
    client, args, judge_config,
    content_id, scene_idx, mode,
    candidate_text, anchor_text,
    file_write_lock
):
    """단일 (scene_idx, mode) Description을 평가하고 결과를 기록합니다."""
    if not anchor_text:
        print(f"  [Warning] Scene {scene_idx}에 KSS Anchor가 없습니다. mode={mode} 스킵.")
        return
    if not candidate_text or not candidate_text.strip():
        print(f"  [Warning] Scene {scene_idx} mode={mode}의 Candidate가 비어있습니다. 스킵.")
        return

    try:
        time.sleep(1)

        score_dict = retry_parse_json(
            lambda: _retry_api_call(
                lambda: client.models.generate_content(
                    model=args.kd_judge_model,
                    contents=[
                        "--- [Anchor] (Ground-truth KeyScene Summary, Korean) ---",
                        anchor_text,
                        "--- [Candidate] (AI-generated Description, English) ---",
                        candidate_text,
                        "--- Request ---",
                        "Evaluate the Candidate description against the Anchor using the 2 criteria defined in the system prompt. "
                        "Output ONLY the JSON with visual_accuracy and contextual_detail scores.",
                    ],
                    config=judge_config
                ).text,
                label=f"KD Judge API ({mode}, Scene {scene_idx})"
            ),
            label=f"KD Judge JSON ({mode}, Scene {scene_idx})"
        )

        # 점수 집계
        _SCORE_KEYS = ["visual_accuracy", "contextual_detail"]
        total = sum(
            (score_dict.get(k, {}).get("score", 0) if isinstance(score_dict.get(k), dict) else 0)
            for k in _SCORE_KEYS
        ) if score_dict else 0

        record = {
            "content_id":  content_id,
            "scene_idx":   scene_idx,
            "mode":        mode,
            "judge":       score_dict,
            "total_score": total,
        }

        # 콘솔 출력
        _ITEM_LABELS = [
            ("visual_accuracy",   "Visual Accuracy (시각 정확도)"),
            ("contextual_detail", "Contextual Detail (컨텍스트 디테일)"),
        ]
        print(f"\n[Judge] Scene {scene_idx} | mode={mode}")
        if score_dict:
            for key, label in _ITEM_LABELS:
                item      = score_dict.get(key, {})
                rationale = item.get("rationale", "N/A") if isinstance(item, dict) else "N/A"
                score     = item.get("score",     "N/A") if isinstance(item, dict) else "N/A"
                print(f"- {label} ({score}/5): {rationale}")
        print(f"-> Total Score: {total}/10")

        append_jsonl(args.output_file, record, lock=file_write_lock)

    except Exception as e:
        print(f"  [Error] Judge 최종 실패 (Scene {scene_idx}, mode={mode}): {e}")


# ───────────────────────────────────────────────
# Main
# ───────────────────────────────────────────────

def main():
    parser = get_common_argparser(description="KeyScene Description 4종을 KSS 앵커 기반으로 품질 평가합니다.")
    parser.add_argument("--kss_file", default="assets/keyscene_summary.jsonl",
                        help="KeyScene Summary JSONL 경로 (Anchor)")
    parser.add_argument("--kd_file", default="assets/keyscene_description.jsonl",
                        help="KeyScene Description JSONL 경로 (video_desc / ref_desc 소스)")
    parser.add_argument("--output_file", default="assets/description_scores.jsonl",
                        help="Description Judge 점수 저장 경로")
    parser.add_argument("--keypoints_file", default="assets/keypoint_scenes.jsonl",
                        help="Keypoint Scene 목록 JSONL 경로")
    parser.add_argument("--watch", action="store_true",
                        help="kd_file을 모니터링하며 새로운 video_desc/ref_desc를 실시간으로 평가합니다.")
    parser.add_argument("--modes", nargs="+",
                        default=["img_desc", "mm_desc", "video_desc", "ref_desc"],
                        choices=["img_desc", "mm_desc", "video_desc", "ref_desc"],
                        help="평가할 모드 직접 지정 (기본값: 4종 모두)")

    args, client = init_pipeline(parser.parse_args())
    judge_config = make_kd_judge_config(thinking_level=args.kd_judge_thinking_level)

    ensure_output_dir(args.output_file)

    # 기처리분 로드: (content_id, scene_idx, mode) 단위
    processed_triples = set()
    for rec in load_jsonl(args.output_file):
        c_id  = rec.get("content_id")
        s_idx = rec.get("scene_idx")
        mode  = rec.get("mode")
        if c_id and s_idx is not None and mode:
            processed_triples.add((c_id, s_idx, mode))
    if processed_triples:
        print(f"[기처리] {len(processed_triples)}개 (content_id, scene_idx, mode) 쌍이 이미 처리됨.")

    # KSS Anchor 로드
    summary_map = load_summary_map(args.kss_file)
    if summary_map:
        print(f"[KSS Anchor] {len(summary_map)}개 Scene의 Summary 로드됨 ({args.kss_file})")
    else:
        print(f"[Warning] KSS 파일을 찾을 수 없거나 비어있습니다: {args.kss_file}")

    # Keypoint 목록 (필요 시 GCS 접근용)
    keypoints_by_content = {}
    if os.path.exists(args.keypoints_file):
        keypoints_by_content = load_keypoints_by_content(args.keypoints_file)

    print_pipeline_banner(
        f"KeyScene Description 품질 평가 파이프라인을 시작합니다. (Watch 모드: {args.watch})"
    )

    file_write_lock = threading.Lock()

    # ── GCS 기반 소스 (img_desc, mm_desc) 처리 ──────────────────
    gcs_modes = [m for m in args.modes if m in ("img_desc", "mm_desc")]

    def process_gcs_modes():
        """GCS에 저장된 img_desc / mm_desc를 content별로 평가합니다."""
        if not gcs_modes or not keypoints_by_content:
            return

        for content_id, keypoints in keypoints_by_content.items():
            # GCS 메타데이터 프리로드
            preload_content_metadata(args.gs_bucket_name, content_id)

            for kp in keypoints:
                real_idx  = keypoints.index(kp)
                scene_idx = kp.get("scene_idx", real_idx)

                # Anchor 추출 (현재 장면 묘사만 사용)
                kss_raw = summary_map.get((content_id, scene_idx), "")
                anchor  = extract_current_scene_desc(kss_raw) if kss_raw else ""

                pending_modes = [
                    m for m in gcs_modes
                    if (content_id, scene_idx, m) not in processed_triples
                ]
                if not pending_modes:
                    continue

                print(f"\nEvaluating '{content_id}' Scene {scene_idx} GCS modes={pending_modes}")

                with concurrent.futures.ThreadPoolExecutor(max_workers=len(pending_modes)) as executor:
                    futures = []
                    for mode in pending_modes:
                        # GCS에서 해당 scene_idx의 description 텍스트 추출
                        candidate = get_gcs_descriptions_by_scene_idx(
                            args.gs_bucket_name, content_id, mode, scene_idx, scene_idx
                        )
                        # [Scene N]\n... 태그 제거하여 순수 텍스트만 사용
                        candidate = "\n".join(
                            line for line in candidate.split("\n")
                            if not line.startswith(f"[Scene {scene_idx}]")
                        ).strip()

                        futures.append(executor.submit(
                            judge_one_description,
                            client, args, judge_config,
                            content_id, scene_idx, mode,
                            candidate, anchor,
                            file_write_lock
                        ))
                    for f in concurrent.futures.as_completed(futures):
                        try:
                            f.result()
                        except Exception as e:
                            print(f"  [Error] GCS mode 평가 실패: {e}")

                with file_write_lock:
                    for mode in pending_modes:
                        processed_triples.add((content_id, scene_idx, mode))

    # GCS 소스 우선 처리 (생성 스크립트와 독립적으로 즉시 평가 가능)
    process_gcs_modes()

    # ── keyscene_description.jsonl 기반 소스 (video_desc, ref_desc) ──
    local_modes = [m for m in args.modes if m in ("video_desc", "ref_desc")]

    if not local_modes:
        print_pipeline_done(args.output_file)
        return

    last_position   = 0
    pipeline_done   = False
    total_evaluated = len(processed_triples)

    try:
        while True:
            if not os.path.exists(args.kd_file):
                if not args.watch:
                    print(f"[Info] {args.kd_file} 파일이 존재하지 않습니다. local mode 평가를 건너뜁니다.")
                    break
                time.sleep(3)
                continue

            with open(args.kd_file, "r", encoding="utf-8") as f:
                f.seek(last_position)
                new_lines    = f.readlines()
                last_position = f.tell()

            new_items = []
            for line in new_lines:
                if not line.strip():
                    continue
                try:
                    obj = json.loads(line)
                    if obj.get("pipeline_done"):
                        pipeline_done = True
                    else:
                        new_items.append(obj)
                except json.JSONDecodeError:
                    pass

            if new_items:
                pending = []
                for item in new_items:
                    c_id  = item.get("content_id")
                    s_idx = item.get("scene_idx")
                    mode  = item.get("mode")
                    if not c_id or s_idx is None or not mode:
                        continue
                    if mode not in local_modes:
                        continue
                    if (c_id, s_idx, mode) in processed_triples:
                        continue
                    pending.append(item)

                if pending:
                    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as executor:
                        futures = []
                        for item in pending:
                            c_id      = item["content_id"]
                            s_idx     = item["scene_idx"]
                            mode      = item["mode"]
                            candidate = item.get("description", "")
                            kss_raw   = summary_map.get((c_id, s_idx), "")
                            anchor    = extract_current_scene_desc(kss_raw) if kss_raw else ""

                            print(f"\nEvaluating '{c_id}' Scene {s_idx} | mode={mode}")
                            futures.append(executor.submit(
                                judge_one_description,
                                client, args, judge_config,
                                c_id, s_idx, mode,
                                candidate, anchor,
                                file_write_lock
                            ))

                        for f in concurrent.futures.as_completed(futures):
                            try:
                                f.result()
                                total_evaluated += 1
                            except Exception as e:
                                print(f"  [Error] local mode 평가 실패: {e}")

                    with file_write_lock:
                        for item in pending:
                            processed_triples.add((item["content_id"], item["scene_idx"], item["mode"]))

                    print(f"\n▶ [Judge TODO] Evaluated so far: {total_evaluated}")

            if args.watch:
                if pipeline_done:
                    print("\n[Watch] Generation 파이프라인 종료 시그널(pipeline_done) 감지. 모든 처리를 완료하고 종료합니다.")
                    break
                time.sleep(3)
            else:
                break

    except KeyboardInterrupt:
        print("\n\n사용자에 의해 중단되었습니다.")
        import os as _os
        _os.exit(1)

    print_pipeline_done(args.output_file)


if __name__ == "__main__":
    main()
